---
- name: Terminate queried instances in {{region}}
  ec2:
    state: 'absent'
    profile: "{{profile}}"
    region: "{{region}}"
    instance_ids: "{{item.id}}"
  with_items: "{{ec2_info.instances}}"
  when: ec2_info.instances|length > 0

- name: Wait for the instance to shutdown
  wait_for:
    host: "{{item.public_ip_address}}"
    port: 22
    state: stopped
    delay: 30
    timeout: 320
  with_items: "{{ec2_info.instances}}"
  when: ec2_info.instances|length > 0

- name: Pause for a minute
  pause:
    seconds: "{{pause_for_down}}" 
  when: ec2_info.instances|length > 0

- name: Get ec2 security group facts (boto3 required)
  ec2_group_facts:
    profile: "{{profile}}"
    region: "{{region}}"
    filters:
      vpc_id: "{{vpc_id}}"
      group_name: "{{sg_name|default(key_name + '_sq')}}"
  register: ec2_sg_info

- name: Take security group down
  ec2_group:
    name: "{{sg_name|default(key_name + '_sq')}}"
    profile: "{{profile}}"
    region: "{{region}}"
    state: 'absent'
  when: ec2_info.instances|length > 0 or ec2_sg_info.security_groups|length > 0
